# Generated by Django 2.2.28 on 2022-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressbbrhszqbzb'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbbrhszqbzb',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
